#! python
"""
This script will autoreload your sphinx documentation each time you refresh
your web browser

Usage:
    autoreload-sphinx <source_dir> [--conf_dir=conf_dir] [--out_dir=out_dir] [--doctree_dir=doctree_dir] [--port=port]

Defaults:
    conf_dir: defaults to source_dir
    out_dir: defaults to source_dir/_build/html
    doctree_dir: defaults to source_dir/.doctree
    port: defaults to 2105
"""

from os.path import join as pjoin

import docopt
arguments = docopt.docopt(__doc__)

out_args = {}
for k, v in arguments.items():
    if v:
        out_args[k.strip('<>-').upper()] = v

def default_value(adict, akey, avalue):
    if not adict.get(akey):
        adict[akey] = avalue

base_dir = out_args['SOURCE_DIR']
default_value(out_args, 'CONF_DIR', base_dir)
default_value(out_args, 'OUT_DIR', pjoin(base_dir, '_build/html'))
default_value(out_args, 'DOCTREE_DIR', pjoin(base_dir, '.doctrees'))

from sphinxautoreload import app
app.run(out_args)
